apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-config
data:
  config: |
    {
      "API": {
        "HTTPHeaders": {
          "Access-Control-Allow-Origin": [
            "*"
          ],
          "Access-Control-Allow-Methods": [
            "POST",
            "GET",
            "OPTIONS"
          ],
          "Access-Control-Allow-Credentials": [
            "true"
          ]
        }
      },
      "Addresses": {
        "Swarm": [
          "/ip4/0.0.0.0/tcp/4001",
          "/ip6/::/tcp/4001"
        ],
        "API": "/ip4/0.0.0.0/tcp/5001",
        "Gateway": "/ip4/0.0.0.0/tcp/8080"
      },
      "Bootstrap": [
        "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfVoEaAETKtPfVxhXa1gW7v2yS8BP1WdnuTGY",
        "/dnsaddr/bootstrap.libp2p.io/p2p/QmU4pCHTm3Te8YiokE1BdRwvhb2ZQ6ZrCVVXjXqXSuGSuX",
        "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb"
      ],
      "Datastore": {
        "StorageMax": "10GB"
      },
      "Swarm": {
        "ConnMgr": {
          "LowWater": 1000,
          "HighWater": 3000
        }
      }
    }
